### ISSUE TITLE
Sentinel failover time is blocking

### ISSUE THREAD

**Issue by knguyen2525** [ortoo/node-redis-sentinel#42]
Hello,

This is more of a best practice question. So I am using Node.js to connect to the the current master as directed by Sentinel, and I am running a LUA script on this master for some bulk insertions.  When the current master fails and Sentinel performs an automatic failover on the Redis side, Node.js naturally cannot contact/perform any commands on the Redis servers.  
What would be the best way to handle this on the Node.js side besides losing the requests that happen during this failover time?

Thanks!

**Comment by jamessharp** [comment]
I think the requests should just be buffered and replayed when a new connection is established. So I don't think it would cause a problem. This library uses the same mechanism as whatever `node_redis` uses when it drops a connection. The only difference is we switch the endpoint locations before a reconnect but everything else is the same.  It could be that LUA scripts are causing problems because there are two mechanisms EVAL and EVALSHA. I think the `node_redis` library tries to be clever and uses EVALSHA if it can, so I can imagine some problems if the redis server switches and no longer knows about your EVAL command. The thing is this is, I reckon this is a similar scenario to a single redis server restarting so probably more of a question for the `node_redis` guys if things aren't working properly.
